### ISSUE TITLE
Documentation suggestion: Add a jsFiddle

### ISSUE THREAD

**Issue by pmorch** [tannernetwork/resizable#3]
Hi,

When I saw this i wasn't really sure what it did. May I ask that a link be added to an online demo?

I made this [jsFiddle](https://jsfiddle.net/pmorch/cv4rvmq3/1/) but any other online demo so one can see and modify the code would be very helpful.

Peter

**Comment by tannernetwork** [comment]
I've added an example based on your fiddle to readme. Thank you very much!
